# Basic
def sendMessage():
    def Mail():...
    def Whastapp():...
    def FaceBook():...

def call():
    def skype():...
    def phone():...
    def zoom():...

def find():
    def storage():...
    def google():...
    def crawler():...
    def youtube():...
    def twitter():...
    def insta():...
    def snap():...

def play():
    def music():...
    def video():...

# Advanced
options = list()

def get(val):
    find()
    play()
    def contact():...
    if val in options:
        def openPDFcompiler():...
        def find():
            return openPDFcompiler()
